make the script functional oriented

diff --git a/modules/ascii_art_fastfetch b/modules/ascii_art_fastfetch
--- a/modules/ascii_art_fastfetch
+++ b/modules/ascii_art_fastfetch
@@ -20,19 +20,27 @@
 }
 
 _get_encoded_url() {
-  url="https://emojicombos.com/api/search?keyphrase=$encoded"
+  url="https://emojicombos.com/api/search?keyphrase=$escaped_search_query"
   wget "$url" -qO - | sed -e 's#https://emojicombos.com/##g'
 }
 
-rp=${rp/#"$_dot_bootstrap_root_"/\$_dot_bootstrap_root_}
 _download_ascii_art() {
-  
-  encoded="$(_get_encoded_url)"
+  [[ -f "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/cached_query" ]] || touch "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/cached_query"
+  if [[ -z "$cached_query" ]] ; then
+    encoded="$(_get_encoded_url)"
+    echo "$escaped_search_query:$encoded" >> "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/cached_query"
+  else
+    encoded="$( cut -d ':' -f2 <<< "$cached_query" )"
+  fi
   url="https://emojicombos.com/$encoded"
   html="$_dot_bootstrap_root_/generated/ascii_art_fastfetch/$encoded.html"
- 
   echo "search     : https://emojicombos.com/api/search?keyphrase=$encoded"
   echo "encoded    : ${encoded/#"$_dot_bootstrap_root_"/\$_dot_bootstrap_root_}"
+  [[ "$encoded" == "https://emojidb.org/"* ]] && {
+    _ascii_art_fastfetch_error_="No webpage found for this query : \"$ASCII_SEARCH_QUERY\""
+    echo "$escaped_search_query" >> "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/failed_queries"
+    return
+  }
   echo "url        : $url"
   echo "html       : ${html/#"$_dot_bootstrap_root_"/\$_dot_bootstrap_root_}"
   echo "output     : ${output/#"$_dot_bootstrap_root_"/\$_dot_bootstrap_root_}"
@@ -40,8 +48,8 @@ _download_ascii_art() {
   [[ -d "$output.temp" ]] || mkdir -p "$output.temp"
   [[ -f "$html" ]] || wget "$url" -O "$html"
   [[ -f "$html.trimmed" ]] || sed -e 's#^[[:space:]]\+\(<[[:space:]]*div\)#\1#g' "$html" > "$html.trimmed"
-  
-  elements=$(htmlq '.emoji-wrap' < "$html.trimmed" )
+
+    elements=$(htmlq '.emoji-wrap' < "$html.trimmed" )
   
   count=$(grep -Po '(?<=class=)"[^"]*emoji-wrap[^"]*"' "$html" | wc -l)
   
@@ -53,7 +61,7 @@ _download_ascii_art() {
 
     # Skip sensitive/explicit entries unless ALLOW_EXPLICIT_ASCII is set.
     [[ ! -v "ALLOW_EXPLICIT_ASCII" ]] && [[ ! -z "$adult_art_encoded_data" ]] && {
-        print -n "\r-> extracting $((i + 1))/$count"
+        print -n -- "\r-> extracting $((i + 1))/$count"
         continue
     }
 
@@ -68,42 +76,64 @@ _download_ascii_art() {
   
     ((saved++))
   
-    print -n "\r-> extracting $((i + 1))/$count"
+    print -n -- "\r-> extracting $((i + 1))/$count"
   done
   
   mv "$output.temp" "$output"
 
-  print
-  print "-> extracted $saved/$count   "
+  print -- "\r-> extracted $saved/$count   \n"
 }
-
-encoded=$(jq -rn --arg v "$ASCII_SEARCH_QUERY" '$v|@uri')
-output="$_dot_bootstrap_root_/generated/ascii_art_fastfetch/$encoded"
-[[ -v "ALLOW_EXPLICIT_ASCII" ]] && output="${output}_explicit"
-
-[[ -d "$output" ]] || _download_ascii_art
 
 _dimension_filter() {
   find "$output" -maxdepth 1 -type f -print0 | xargs -0 -n1 sh -c 'wc -l "$1" | cut -d " " -f1 | tr "\n" ":" ; awk "length > max { max = length } END { print max }" "$1" | tr "\n" ":" ; echo "$1"' _ | tr '\n' '\0' | xargs -0 -n1 sh -c 'dimension=() ; dimension[0]="$(echo "$1" | cut -d ':' -f1 )"; dimension[1]="$(echo "$1" | cut -d ':' -f2 )" ;  dimension[2]="$(echo "$1" | cut -d ':' -f3 )" ; if (( "${dimension[0]}" <= ASCII_DIMENSION_HEIGHT )) && (( "${dimension[1]}" <= ASCII_DIMENSION_WIDTH )) ; then echo "${dimension[2]}" ; fi' _
 }
 
-if [[ "$ASCII_DIMENSION_HEIGHT" == *[!$' \t\r\n']* ]] && [[ "$ASCII_DIMENSION_WIDTH" == *[!$' \t\r\n']* ]] ; then
-  local dimension_output="${output}_${ASCII_DIMENSION_HEIGHT}x${ASCII_DIMENSION_WIDTH}"
-  [[ -d "$dimension_output" ]] || {
-    echo "filtering  : ${ASCII_DIMENSION_HEIGHT}x${ASCII_DIMENSION_WIDTH}"
-    mkdir -p "$dimension_output.temp"
-    local saved=0
-    local total="$( ls "$output" | wc -l | cut -d ' ' -f1 )"
-    _dimension_filter | while IFS= read -r file; do 
-      file_name="${file##*/}"
-      print -n "\r-> copying $file_name           "
-      cp "$file" "$dimension_output.temp/$file_name"
-      ((saved++))
-    done
-    print "\nfiltered   : $saved/$total"
-    mv "$dimension_output.temp" "$dimension_output"
+_ascii_art_refresh_() {
+  [[ -d "$_dot_bootstrap_root_/generated/ascii_art_fastfetch" ]] || mkdir -p "$_dot_bootstrap_root_/generated/ascii_art_fastfetch"
+  unset _ascii_art_fastfetch_error_
+  escaped_search_query=$(jq -rn --arg v "$ASCII_SEARCH_QUERY" '$v|@uri')
+  output="$_dot_bootstrap_root_/generated/ascii_art_fastfetch/$escaped_search_query"
+  [[ -v "ALLOW_EXPLICIT_ASCII" ]] && output="${output}_explicit"
+  [[ -f "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/failed_queries" ]] || touch "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/failed_queries"
+  grep -q "^$escaped_search_query$" "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/failed_queries" && {
+    _ascii_art_fastfetch_error_="This query had no result : \"$ASCII_SEARCH_QUERY\""
+    return
   }
-  ls "$dimension_output" | shuf -n 1 | tr '\n' '\0' | xargs -0 sh -c "cat \"$output/\$1\"" _ | fastfetch --file - 
-else
-  ls "$output" | shuf -n 1 | tr '\n' '\0' | xargs -0 sh -c "cat \"$output/\$1\"" _ | fastfetch --file - 
-fi
+  [[ -d "$output" ]] || _download_ascii_art
+  [[ -v _ascii_art_fastfetch_error_ ]] && return
+  _ascii_art_dir_="$output"
+  if [[ "$ASCII_DIMENSION_HEIGHT" == *[!$' \t\r\n']* ]] && [[ "$ASCII_DIMENSION_WIDTH" == *[!$' \t\r\n']* ]] ; then
+    local dimension_output="${output}_${ASCII_DIMENSION_HEIGHT}x${ASCII_DIMENSION_WIDTH}"
+    [[ -d "$dimension_output" ]] || {
+      echo "filtering  : ${ASCII_DIMENSION_HEIGHT}x${ASCII_DIMENSION_WIDTH}"
+      mkdir -p "$dimension_output.temp"
+      local saved=0
+      local total="$( ls "$output" | wc -l | cut -d ' ' -f1 )"
+      _dimension_filter | while IFS= read -r file; do
+        file_name="${file##*/}"
+        print -n "\r-> copying $file_name           "
+        cp "$file" "$dimension_output.temp/$file_name"
+        ((saved++))
+      done
+      print "\rfiltered   : $saved/$total            \n"
+      mv "$dimension_output.temp" "$dimension_output"
+    }
+    _ascii_art_dir_="$dimension_output"
+  fi
+}
+
+:ascii-art-refresh() {
+  _ascii_art_refresh_
+}
+
+:ascii-art-fastfetch() {
+  [[ -v _ascii_art_fastfetch_error_ ]] && {
+    echo "$_ascii_art_fastfetch_error_ "
+    echo "change query then \":ascii-art-refresh && :ascii-art-fastfetch\""
+    return
+  }
+  ls "$_ascii_art_dir_" | shuf -n 1 | tr '\n' '\0' | xargs -0 sh -c "cat \"$output/\$1\"" _ | fastfetch --file -
+}
+
+_ascii_art_refresh_
+:ascii-art-fastfetch
