if a snapshot already exist move it to tail

diff --git a/runtime/fingerprint/check_last_generation b/runtime/fingerprint/check_last_generation
--- a/runtime/fingerprint/check_last_generation
+++ b/runtime/fingerprint/check_last_generation
@@ -3,23 +3,27 @@
 current_hash="$( source "$_dot_bootstrap_root_/runtime/generator/config_module_hash" )"
 
 [[ -f "$_dot_bootstrap_root_/generated/failure_hash" ]] && {
-  failure_hash="$( head -n1 "$_dot_bootstrap_root_/generated/failure_hash" )"
-  [[ "$current_hash" == "$failure_hash" ]] && {
-    echo "[fingerprint/check_last_generation] this snapshot has already failed previously : $( tail -n1 "$_dot_bootstrap_root_/generated/failure_hash" )" | error
-    echo "[fingerprint/check_last_generation] failure_hash : $failure_hash " | error
-    echo "[fingerprint/check_last_generation] current_Hash : $current_hash " | error
+  failure_entry="$( grep "^${current_hash}:.\+" "$_dot_bootstrap_root_/generated/failure_hash" )"
+  [[ -z "$failure_entry" ]] || {
+    echo "[fingerprint/check_last_generation] this snapshot has already failed previously : $( cut -d ":" -f2 <<< "$failure_entry" )" | error
+    echo "[fingerprint/check_last_generation] current_Hash : '$current_hash' " | error
+    echo "[fingerprint/check_last_generation] failure_entry : '$failure_entry' " | error
     generation_error="[fingerprint/check_last_generation_failure_status] this snapshot has already failed previously"
     export no_generation_required
     return
   }
 }
 
-[[ -f "$_dot_bootstrap_root_/generated/last_generation" ]] && {
-  last_generation="$( head -n1 "$_dot_bootstrap_root_/generated/last_generation" )"
-  [[ "$current_hash" == "$last_generation" ]] && {
-    echo "[fingerprint/check_last_generation] no change to the module config : $( tail -n1 "$_dot_bootstrap_root_/generated/last_generation" )" | debug
-    echo "[fingerprint/check_last_generation] last_generation : $last_generation " | debug
-    echo "[fingerprint/check_last_generation] current_Hash : $current_hash " | debug
+[[ -f "$_dot_bootstrap_root_/generated/snapshots" ]] && {
+  snapshot_entry="$( grep "^.\+:$current_hash$" "$_dot_bootstrap_root_/generated/snapshots" | tail -n1 )"
+  [[ -z "$snapshot_entry" ]] || {
+    echo "[fingerprint/check_last_generation] no change to the module config : $( cut -d':' -f1 <<< "$snapshot_entry" )" | debug
+    echo "[fingerprint/check_last_generation] current_Hash : '$current_hash' " | debug
+    echo "[fingerprint/check_last_generation] past_generation : '$snapshot_entry' " | debug
+    tail -n1 "$_dot_bootstrap_root_/generated/snapshots" | grep -Fq "$snapshot_entry" || {
+      echo "[fingerprint/check_last_generation] moving entry to tail" | debug
+      source "$_dot_bootstrap_root_/runtime/generator/reuse_snapshot"
+    }
     export no_generation_required
   }
 }
