generate artifact

diff --git a/runtime/generator/module b/runtime/generator/module
--- a/runtime/generator/module
+++ b/runtime/generator/module
@@ -1,5 +1,41 @@
 #!/bin/env zsh
 
-[[ -d "$_dot_bootstrap_root_/generated/$_session_id_/scripts" ]] || mkdir -p "$_dot_bootstrap_root_/generated/$_session_id_/scripts"
+local index="$( echo $module | awk -F ':' '{ print $1 }' )" 
+local name="$( echo $module | awk -F ':' '{ print $2 }' )"
+local hash="$( echo $module | awk -F ':' '{ print $3 }' )"
 
-echo "[generator/module] generation required for module $module" | debug
+[[ -d "$_dot_bootstrap_root_/generated/$_session_id_/scripts/$index" ]] || mkdir -p "$_dot_bootstrap_root_/generated/$_session_id_/scripts/$index"
+
+echo "[generator/module] generation required for module $name" | debug
+
+[[ "$($_dot_bootstrap_root_/runtime/analyzer/is_script_parsable $_dot_bootstrap_root_/modules/$name)" ]] || {
+  echo "[generator/module] script $name failed to load" | error
+  return
+}
+
+grep -q '^# *@nolazy' "$_dot_bootstrap_root_/modules/$name" && {
+  echo "[generator/module] copying $name @nolazy tag found" | debug
+  cp $_dot_bootstrap_root_/modules/$name $_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/main
+  return
+}
+
+grep -q '^# *@lazy' "$_dot_bootstrap_root_/modules/$name" && {
+  echo "[generator/module] generating lazy stub for $name @lazy tag found" | debug
+  cp $_dot_bootstrap_root_/modules/$name $_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/lazy
+  $_dot_bootstrap_root_/runtime/generator/helper/lazyWrapperGenerator $_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/lazy > $_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/main
+  return
+}
+
+echo "[generator/module] doing automatic optimization" | debug
+lazy_funcs="$( $_dot_bootstrap_root_/runtime/analyzer/lazy_funcs $_dot_bootstrap_root_/modules/$name)"
+
+[[ -z $lazy_funcs ]] && {
+  echo "[generator/module] no lazy func found copying $name" | debug
+  cp $_dot_bootstrap_root_/modules/$name $_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/main
+  return
+}
+
+echo "[generator/module] lazy func found for $name : $lazy_funcs" | debug
+$_dot_bootstrap_root_/runtime/generator/helper/extract_func $_dot_bootstrap_root_/modules/$name $lazy_funcs > $_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/lazy_funcs
+$_dot_bootstrap_root_/runtime/generator/helper/remove_func $_dot_bootstrap_root_/modules/$name $lazy_funcs > $_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/main
+$_dot_bootstrap_root_/runtime/generator/helper/lazyWrapperGenerator $_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/lazy_funcs >> $_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/main
diff --git a/runtime/initialize/init_logger b/runtime/initialize/init_logger
--- a/runtime/initialize/init_logger
+++ b/runtime/initialize/init_logger
@@ -7,14 +7,12 @@ BLUE="\e[1;34m"
 RESET="\e[0m"
 mkdir -p $_log_dir_
 
-if [[ -v SILENT_LOG ]]; then
-  touch $_log_dir_/$_session_id_
-  exec {logger}> "$_log_dir_/$_session_id_"
-fi
+touch $_log_dir_/$_session_id_
+exec {logger}> "$_log_dir_/$_session_id_"
 
 on_logger_exit() {
   echo "Script finished! Running post-script task..."
-  if [[ -f "$_log_dir_/$_session_id_" && -v SILENT_LOG ]]; then
+  if [[ -f "$_log_dir_/$_session_id_" ]]; then
     echo "executed exit trap" | debug
     exec {logger}>&-
     rm $_log_dir_/$_session_id_
@@ -30,33 +28,23 @@ trap on_logger_exit EXIT INT TERM
 export error() {
   local input=$(cat)
   if [[ -v LOGERROR ]] ; then
-    if [[ -v SILENT_LOG ]] ; then
-      printf "${RED}[ERROR]${RESET} %s\n" "$input" >&$logger
-    else
-      printf "${RED}[ERROR]${RESET} %s\n" "$input" >&2
-    fi
+    printf "${RED}[ERROR]${RESET} %s\n" "$input" >&$logger
+    [[ -v SILENT_LOG ]] || printf "${RED}[ERROR]${RESET} %s\n" "$input" >&2
   fi
 }
 
 export warn() {
   local input=$(cat)
   if [[ -v LOGERROR ]] || [[ -v LOGWARN ]] ; then
-    if [[ -v SILENT_LOG ]] ; then
-      printf "${YELLOW}[WARN]${RESET} %s\n" "$input" >&$logger
-    else
-      printf "${YELLOW}[WARN]${RESET} %s\n"  "$input" >&2
-    fi
+    printf "${YELLOW}[WARN]${RESET} %s\n" "$input" >&$logger
+    [[ -v SILENT_LOG ]] || printf "${YELLOW}[WARN]${RESET} %s\n"  "$input" >&2
   fi
 }
 
 export debug() {
   local input=$(cat)
   if [[ -v LOGERROR ]] || [[ -v LOGWARN ]] || [[ -v LOGDEBUG ]] ; then
-    if [[ -v SILENT_LOG ]] ; then
-      printf "${BLUE}[DEBUG]${RESET} %s\n" "$input" >&$logger
-    else
-      printf "${BLUE}[DEBUG]${RESET} %s\n" "$input" 
-    fi
+    printf "${BLUE}[DEBUG]${RESET} %s\n" "$input" >&$logger
+    [[ -v SILENT_LOG ]] || printf "${BLUE}[DEBUG]${RESET} %s\n" "$input" 
   fi
 }
-
